---
- name: Playbook with variables, debug, set_fact
  hosts: all
  become: yes

  vars:
    message1: "Hello,"
    message2: "World!"

  tasks:
  - name: Print variables
    debug:
      var: message
  - debug:
      msg: "{{ message1 }}, World!"

  - set_fact: full_message="{{ message1 }} {{ message2 }} from user"
  - debug:
      var: full_message
  - debug:
      var: ansible_distribution

  - shell: uptime
    #записываем вывод команды uptime в перемеонную my_uptime
    register: my_uptime
  - debug:
      var: my_uptime.stdout