---
- name: Loops
  hosts: all
  become: yes

  tasks:
  - name: Say hello for everybody
    debug: msg="hello {{ item }}"
    loop:
      - "One"
      - "Two"
      - "Three"

  - name: Until loop
    shell: echo -n Zz >> myfile.txt && cat myfile.txt
    register: output
    #задержка между loops в секундах
    delay: 1
    #Максимальное количество попыток
    retries: 5
    until: output.stdout.find('ZzZzZz') == false
    debug:
      var: output.stdout
