---
- name: Setting up server
  hosts: all
  become: yes
  tasks:
  - name: 'Changing server name to: {{ server_name }}'
    hostname: name="{{ server_name }}"
  - name: 'Create user: {{ new_user }}'
    user:
      name: "{{ new_user }}"
      password: "{{ user_password | password_hash('sha512') }}"
